### ISSUE TITLE
Error when external url mode with URL parameters

### ISSUE THREAD

**Issue by ivan909020** [microsoft/jmeter-performance-analyzer-devops-extension#16]
Build error when I specify "JMeter Property Source URL" and "JMX Input File(s) Source URL Comma Separated" with URLs from Azure Blob Storage. I think it is happening because it tries to get the filename from the URL with parameters.

URL:
https://blob.core.windows.net/input.properties?sp=r&spr=https...

Message:
##[error]Error: ENOENT: no such file or directory, open 'D:\a\r1\a\apache-jmeter-5.5\bin\input.properties?sp=r&spr=https...

---

Also, it would be great to add "Inline" mode, to be able specify properties inside the script.

**Comment by 5-k** [comment]
Hi there, 
We will be updating you on the fix by end of the week

**Comment by 5-k** [comment]
Hi there, can you send the yml file or pipeline configuration for which you are facing the issue

**Comment by ivan909020** [comment]
> Hi there, can you send the yml file or pipeline configuration for which you are facing the issue

steps:
- task: id-az-pipeline.jmeter-perf-analyzer.custom-build-release-task.perfanalyzer@1
  displayName: 'Run Perf Analyzer'
  inputs:
    jmxsourceRunFilePath: '$(System.DefaultWorkingDirectory)/drop/test-performance/test.jmx'
    jmxPropertySource: url
    jmxPropertySourceURL: 'https://blob.core.windows.net/performance-testing/test/input.properties?sp=r&spr=https&sv=...'
    jmxInputFilesSource: urls
    jmxInputFilesUrls: 'https://blob.core.windows.net/performance-testing/accounts.csv?sp=r&spr=https&sv=...'
    publishResultsToBuildArtifact: false

**Comment by 5-k** [comment]
Hi ,

Can you share the complete urls for properties file and input files?

**Comment by ivan909020** [comment]
> Hi ,
> 
> Can you share the complete urls for properties file and input files?

Sorry I don't have them anymore, deleted blob storage and ended up using repos

**Comment by 5-k** [comment]
The urls should be public urls that when you put in your browser starts to download. 
If multiple input files are present, then it these absolute urls must be comma separated.

I will however test the scenario you mentioned.

Also regarding the inline property file, that is possible however for input files, specially if multiple, i need to recheck if that is even possible

**Comment by ivan909020** [comment]
> The urls should be public urls that when you put in your browser starts to download. If multiple input files are present, then it these absolute urls must be comma separated.
> 
> I will however test the scenario you mentioned.
> 
> Also regarding the inline property file, that is possible however for input files, specially if multiple, i need to recheck if that is even possible

The urls were public, I generated them using SAS token.

**Comment by 5-k** [comment]
If possible can you put in some dummy file and share the links, i will try to reproduce the error

**Comment by ivan909020** [comment]
> If possible can you put in some dummy file and share the links, i will try to reproduce the error

You can try this. The link is not to the blob storage, but I added similar parameters which blob storage uses.

https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64.sha256?comp=properties&sv=2015-04-05&ss=bf&srt=s&st=2015-04-29T22%3A18%3A26Z&se=2015-04-30T02%3A23%3A26Z&sr=b&sp=rw&sip=168.1.5.60-168.1.5.70&spr=https&sig=F%6GRVAZ5Cdj2Pw4tgU7IlSTkWgn7bUkkAg8P6HESXwmf%4B

**Comment by 5-k** [comment]
I have deployed version 1.5.52 , could you please verify if the bug fix has resolved the issue

**Comment by ivan909020** [comment]
> I have deployed version 1.5.52 , could you please verify if the bug fix has resolved the issue

Hello, I will check it tomorrow

**Comment by ivan909020** [comment]
@5-k It seems to be resolved.

**Comment by 5-k** [comment]
Marking it as resolved
Thanks for the update
