### ISSUE TITLE
PerfAnalyzerLogs and PerfAnalyzerReport contain the same data

### ISSUE THREAD

**Issue by boitcex** [microsoft/jmeter-performance-analyzer-devops-extension#9]
**Summary**: PerfAnalyzerLogs and PerfAnalyzerReport contain the same data running the test from Azure pipeline using stansart configurations.
**Expected result:**
PerfAnalyzerLogs - test execution and jtl
PerfAnalyzerReport  - output html report
![config](https://user-images.githubusercontent.com/2488949/189675946-76110c2a-a05a-4203-8cca-71db850a2fdd.png)
![artifact](https://user-images.githubusercontent.com/2488949/189675953-a56eab85-b2ab-4df8-9502-1811afeab475.png)

**Comment by 5-k** [comment]
Hi there,

Thanks for the update. Will be fixing and providing the update in next 2 days

**Comment by boitcex** [comment]
![image](https://user-images.githubusercontent.com/2488949/189679649-db56f019-f50c-43c5-b473-cdbbd3c10378.png)
![image](https://user-images.githubusercontent.com/2488949/189679777-36566a3c-0043-43f3-9e1b-bf137a3c5a34.png)

**Comment by 5-k** [comment]
Fixed in version 1.5.48
Use the latest version. This is available and published now
